# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: emallah <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/10/19 19:42:32 by emallah           #+#    #+#              #
#    Updated: 2020/10/19 19:42:49 by emallah          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# all: $(NAME)

# FILES = ft_err.c get_next_line.c get_next_line_utils.c ft_err.c ft_atoi.c ft_color.c ft main.c\
# 		ft_info_reader.c ft_read_file.c ft_resolution.c ft_split.c ft_strtrim.c ft_utile.c
	
# $(NAME):
	# @gcc -Wall -Wextra -Werror $(FILES) -L.. -lmlx -L/usr/include -lXext -lX11 -lm
	# gcc -Werror -Wall -Wextra *.c -lmlx -framework OpenGL -framework AppKit
# clean:
# 	rm a.out

# re: clean all

all:
	gcc -Werror -Wall -Wextra *.c -lmlx -framework OpenGL -framework AppKit